sudo: false
cache: packages

language: r

r_github_packages:
  - jimhester/covr

# Run R package checks and tests against 3 R versions
r:
  - oldrel
  - release
  - devel

before_script:
  - if [ -n "TRAVIS_TAG" ]; then echo $TRAVIS_REPO_SLUG - $TRAVIS_TAG > ./release.txt; fi

# Create Github releases when successful tagged builds are pushed
deploy:
   provider: releases
   api_key:
       secure: "H7oqoiTw26HFaWpRNUR5lGNJfT0xueQsEKq5HtnYqKdXmeCQfCM316xf8sxo7HHZbSa4N0xwavHeC7qlqXiuAEtgmGZGZAXcoNY5eNcGV/yN/tfNiLuW2VpKWkdhsTrwRp9/nvHngsW1Jx00BTIFTpRLc61iO+j+ejPGXdC/c2RpcmqhJrZudhkS6oQDhENicaTjznsvdMIE0C2o5ampc3UWzsizzKyP1xdQjeFvijmWkpjoSMpLWzL32A8IDiriA5An1mmnnDG/DxEU2tcE9Uer+eef40kg7+/9BZ/Zuy4poN6D1AkZsifffIdTB4HstU6OVYXkQqQRTFthgwvDeSpXYxovLjvr0RosFbvoUxaRPK1MxKuo7F0EbsrzsswnJgWqefybdVGWiwH3BO9JAItfCZBBYaWKTo3OUFrLGYUQk78XKhbfxDgd30dwClYrT0O1PzbIhez+dX6VO3/oSk5lfa/8nlAfAnAP64xm2OSZd/JS3g6LWs9VLsop0gidMQotPjcWvnw6MYy50bxED++18EU4ze/HFnvsWJrfCtqglWY+dCz2Cn3eMU7jvEsqcjCKkg15/h8S0lQpooQWlmBuFDWNRL+N+FtBcq194TdJUWDV9fjp0U2/+IZ6zHeUaeSzIOb54Bbhn/NwIqgWU6rU/Pye62E0BZ7c/ui/x+I="
   skip_cleanup: true
   files:
    - ./release.txt
   on:
       repo: hms-dbmi/r_testing
       tags: true

# Upload CodeCov information
after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    - scottx611x@gmail.com