sudo: false
cache: packages

language: r

r_github_packages:
  - jimhester/covr

# Run R package checks and tests against 3 R versions
r:
  - oldrel
  - release
  - devel

# Upload CodeCov information
after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    - scottx611x@gmail.com
